---
# PHP Debian Specific Things

- name: Install Packages
  apt: name={{ item }} state=installed
  with_items:
      - php5-fpm
      - php5-gd
      - php5-mysql 
      - php5-json

- name: Ensure php.ini present for Debian
  template: src=php.ini dest=/etc/php5/{{ item }}/php.ini owner=root group=root mode=0644
  notify: restart php-fpm_deb
  with_items:
    - fpm

- name: Start the php-fpm service
  service: name=php5-fpm state=running enabled=yes
