---
- name: restart nginx
  service: name=nginx enabled=yes state=restarted

- name: reload nginx
  service: name=nginx state=reloaded

- name: restart rsyslog
  service: name=rsyslog state=restarted
