---
# tasks file for mysql
- name: Add the percona key to APT
  apt_key: id=1C4CBDCDCD2EFD2A keyserver=hkp://keyserver.ubuntu.com:80 state=present

- name: Add the percona Apt repo
  apt_repository: repo="deb http://repo.percona.com/apt {{ ansible_distribution_release }} main" state=present update_cache=yes

- name: Create the mysql_root_password based on the variables
  template: src=debconf-set-selections-mysql.conf.j2 dest=/root/mysql-set-selections.conf owner=root group=root mode=0600
  when: mysqlserver == True

- name: Set selections based on the config file
  command: debconf-set-selections /root/mysql-set-selections.conf
  when: mysqlserver == True

- name: Install PerconaDB and client libraries
  apt: name={{ item }} state=present
  with_items:
      - percona-xtradb-cluster-full-56
  when: mysqlserver == True

- name: Install Percona Client Libraries
  apt: name={{ item }} state=present
  with_items:
      - percona-xtradb-cluster-client-5.6
      - python-mysqldb

- name: Configure the system with sensible defaults
  template: src=my.cnf dest=/etc/mysql/my.cnf owner=root group=root mode=0640
  when: mysqlserver == True
#  notify: restart mysql
